# Minimal, quick run to check everything is wired correctly
seed: 1337
mode: fast                   # "fast" or "full"
fast_n_targets: 20           # sample 20 targets only
fast_repeats: 1              # one pass over the sample
full_repeats: 1
hard_mode: false
allow_probes: false          # cheaper (no off-candidate probes)
mcts:
  rollouts_per_move: 10      # tiny MCTS budget for smoke speed
  ucb_c: 1.4
analysis:
  log_turns: false           # turn off per-turn logging for speed
  topk: 3
