seed: 1337
mode: full
fast_n_targets: 200          # unused in "full", kept for parity
fast_repeats: 1              # unused in "full"
full_repeats: 1
hard_mode: false
allow_probes: true           # match your dissertation’s main setting
mcts:
  rollouts_per_move: 400
  ucb_c: 1.4
analysis:
  log_turns: true            # keep on for richer Results
  topk: 10
