mode: full
# Exhaustive benchmark over the full target list
n_targets: all
# More repeats give more stable statistics
repeats: 10
workers: 1
solvers: ["random", "heuristic", "positional", "entropy", "mcts"]
log_turns: false
write_ci: true
make_plots: true
results_dir: results/summary

