fast_dev:
  mode: "fast"
  fast_n_targets: 200
  fast_repeats: 20
  full_repeats: 1
  hard_mode: false
  allow_probes: true
  mcts: { rollouts_per_move: 100, ucb_c: 1.4 }
  analysis: { log_turns: true, topk: 10 }

full_benchmark:
  mode: "full"
  fast_n_targets: 200
  fast_repeats: 1
  full_repeats: 1
  hard_mode: false
  allow_probes: true
  mcts: { rollouts_per_move: 400, ucb_c: 1.4 }
  analysis: { log_turns: true, topk: 10 }
