mode: smoke
# Quick check across all solvers using a small subset of targets
n_targets: 20
repeats: 1
workers: 1
solvers: ["random", "heuristic", "positional", "entropy", "mcts"]
log_turns: false
allow_probes: false
mcts:
  rollouts_per_move: 5
entropy_max_candidates: 500
# Produce confidence intervals and figures for basic verification
write_ci: true
make_plots: true
results_dir: results/summary

