# TODO: paste Solver base + Random/Heuristic/Entropy/MCTS implementations here
class Solver: ...
class RandomSolver(Solver): ...
class HeuristicSolver(Solver): ...
class EntropySolver(Solver): ...
class MCTSSolver(Solver): ...
